services:
  - type: web
    name: ymcs-shield-backend
    runtime: node
    rootDir: waf-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 4000
      - key: REDIS_URL
        fromService:
          type: redis
          name: ymcs-shield-redis
          property: connectionString
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RENDER
        value: "true"
      - key: EMAIL_USER
        sync: false
    healthCheckPath: /health

  - type: redis
    name: ymcs-shield-redis
    ipAllowList: []
